{
  "uid" : "1330d40f5b83a04",
  "name" : "Проверка перехода в Рабочие пространства по ссылке На главную",
  "fullName" : "tests.test_workspace_page.test_workspace_page.TestWorkspacePage#test_link_to_main",
  "historyId" : "11b6f02ab206056145597ed767926875",
  "time" : {
    "start" : 1714357276030,
    "stop" : 1714357276030,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome-headless-shell=124.0.6367.60)\nStacktrace:\n#0 0x559dc2a03e33 <unknown>\n#1 0x559dc26f3567 <unknown>\n#2 0x559dc26eb879 <unknown>\n#3 0x559dc26db852 <unknown>\n#4 0x559dc26dce44 <unknown>\n#5 0x559dc26dbbbe <unknown>\n#6 0x559dc26db2e0 <unknown>\n#7 0x559dc26db181 <unknown>\n#8 0x559dc26d90ec <unknown>\n#9 0x559dc26d960a <unknown>\n#10 0x559dc26f5eef <unknown>\n#11 0x559dc277f695 <unknown>\n#12 0x559dc2760362 <unknown>\n#13 0x559dc277eae2 <unknown>\n#14 0x559dc2760103 <unknown>\n#15 0x559dc27311ba <unknown>\n#16 0x559dc2731b8e <unknown>\n#17 0x559dc29c859b <unknown>\n#18 0x559dc29cc34b <unknown>\n#19 0x559dc29b4681 <unknown>\n#20 0x559dc29cceb2 <unknown>\n#21 0x559dc29996af <unknown>\n#22 0x559dc29f3428 <unknown>\n#23 0x559dc29f3600 <unknown>\n#24 0x559dc2a02f84 <unknown>\n#25 0x7fe571894ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e94810f09cac3ec9eb5063de396cb52a\")>\n\n    @pytest.fixture(scope='function')\n    def auth_user(driver):\n        page_auth_user = LoginPage(driver)\n>       driver.get(Constant.LOGIN_PAGE)\n\ntests/conftest.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:356: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f7971c48bf0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x559dc29f3600 \\\\u003Cunknown>\\\\n#24 0x559dc2a02f84 \\\\u003Cunknown>\\\\n#25 0x7fe571894ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome-headless-shell=124.0.6367.60)\nE       Stacktrace:\nE       #0 0x559dc2a03e33 <unknown>\nE       #1 0x559dc26f3567 <unknown>\nE       #2 0x559dc26eb879 <unknown>\nE       #3 0x559dc26db852 <unknown>\nE       #4 0x559dc26dce44 <unknown>\nE       #5 0x559dc26dbbbe <unknown>\nE       #6 0x559dc26db2e0 <unknown>\nE       #7 0x559dc26db181 <unknown>\nE       #8 0x559dc26d90ec <unknown>\nE       #9 0x559dc26d960a <unknown>\nE       #10 0x559dc26f5eef <unknown>\nE       #11 0x559dc277f695 <unknown>\nE       #12 0x559dc2760362 <unknown>\nE       #13 0x559dc277eae2 <unknown>\nE       #14 0x559dc2760103 <unknown>\nE       #15 0x559dc27311ba <unknown>\nE       #16 0x559dc2731b8e <unknown>\nE       #17 0x559dc29c859b <unknown>\nE       #18 0x559dc29cc34b <unknown>\nE       #19 0x559dc29b4681 <unknown>\nE       #20 0x559dc29cceb2 <unknown>\nE       #21 0x559dc29996af <unknown>\nE       #22 0x559dc29f3428 <unknown>\nE       #23 0x559dc29f3600 <unknown>\nE       #24 0x559dc2a02f84 <unknown>\nE       #25 0x7fe571894ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver",
    "time" : {
      "start" : 1714357276031,
      "stop" : 1714357276228,
      "duration" : 197
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1714357159972,
      "stop" : 1714357159973,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1714357159955,
      "stop" : 1714357159972,
      "duration" : 17
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "auth_user",
    "time" : {
      "start" : 1714357276228,
      "stop" : 1714357276382,
      "duration" : 154
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome-headless-shell=124.0.6367.60)\nStacktrace:\n#0 0x559dc2a03e33 <unknown>\n#1 0x559dc26f3567 <unknown>\n#2 0x559dc26eb879 <unknown>\n#3 0x559dc26db852 <unknown>\n#4 0x559dc26dce44 <unknown>\n#5 0x559dc26dbbbe <unknown>\n#6 0x559dc26db2e0 <unknown>\n#7 0x559dc26db181 <unknown>\n#8 0x559dc26d90ec <unknown>\n#9 0x559dc26d960a <unknown>\n#10 0x559dc26f5eef <unknown>\n#11 0x559dc277f695 <unknown>\n#12 0x559dc2760362 <unknown>\n#13 0x559dc277eae2 <unknown>\n#14 0x559dc2760103 <unknown>\n#15 0x559dc27311ba <unknown>\n#16 0x559dc2731b8e <unknown>\n#17 0x559dc29c859b <unknown>\n#18 0x559dc29cc34b <unknown>\n#19 0x559dc29b4681 <unknown>\n#20 0x559dc29cceb2 <unknown>\n#21 0x559dc29996af <unknown>\n#22 0x559dc29f3428 <unknown>\n#23 0x559dc29f3600 <unknown>\n#24 0x559dc2a02f84 <unknown>\n#25 0x7fe571894ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/PulseWave/PulseWave/tests/conftest.py\", line 10, in auth_user\n    driver.get(Constant.LOGIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1714357276413,
      "stop" : 1714357276471,
      "duration" : 58
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Тестирование страницы 'Рабочие пространства'"
  }, {
    "name" : "tag",
    "value" : "regress"
  }, {
    "name" : "parentSuite",
    "value" : "tests.test_workspace_page"
  }, {
    "name" : "suite",
    "value" : "test_workspace_page"
  }, {
    "name" : "subSuite",
    "value" : "TestWorkspacePage"
  }, {
    "name" : "host",
    "value" : "fv-az842-111"
  }, {
    "name" : "thread",
    "value" : "2300-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_workspace_page.test_workspace_page"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "browser",
    "value" : "'chrome'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 9,
        "unknown" : 0,
        "total" : 13
      },
      "items" : [ {
        "uid" : "50769e067685c258",
        "reportUrl" : "https://Nat754.github.io/PulseWave/8//#testresult/50769e067685c258",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55c5a56f6e33 <unknown>\n#1 0x55c5a53e6567 <unknown>\n#2 0x55c5a543127d <unknown>\n#3 0x55c5a5431331 <unknown>\n#4 0x55c5a5474624 <unknown>\n#5 0x55c5a545338d <unknown>\n#6 0x55c5a5471ae2 <unknown>\n#7 0x55c5a5453103 <unknown>\n#8 0x55c5a54241ba <unknown>\n#9 0x55c5a5424b8e <unknown>\n#10 0x55c5a56bb59b <unknown>\n#11 0x55c5a56bf34b <unknown>\n#12 0x55c5a56a7681 <unknown>\n#13 0x55c5a56bfeb2 <unknown>\n#14 0x55c5a568c6af <unknown>\n#15 0x55c5a56e6428 <unknown>\n#16 0x55c5a56e6600 <unknown>\n#17 0x55c5a56f5f84 <unknown>\n#18 0x7fd279294ac3 <unknown>",
        "time" : {
          "start" : 1714274525577,
          "stop" : 1714274525577,
          "duration" : 0
        }
      }, {
        "uid" : "613f68d1ec407ee5",
        "reportUrl" : "https://Nat754.github.io/PulseWave/7//#testresult/613f68d1ec407ee5",
        "status" : "passed",
        "time" : {
          "start" : 1714185439425,
          "stop" : 1714185439870,
          "duration" : 445
        }
      }, {
        "uid" : "d0dc36a7f3050eee",
        "reportUrl" : "https://Nat754.github.io/PulseWave/6//#testresult/d0dc36a7f3050eee",
        "status" : "passed",
        "time" : {
          "start" : 1714148846656,
          "stop" : 1714148847086,
          "duration" : 430
        }
      }, {
        "uid" : "3350059b01b9ee84",
        "reportUrl" : "https://Nat754.github.io/PulseWave/6//#testresult/3350059b01b9ee84",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome-headless-shell=124.0.6367.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x564343590e33 <unknown>\n#1 0x564343280567 <unknown>\n#2 0x564343285b05 <unknown>\n#3 0x56434328787f <unknown>\n#4 0x56434328790c <unknown>\n#5 0x5643432d140d <unknown>\n#6 0x5643432d07f6 <unknown>\n#7 0x5643433143c5 <unknown>\n#8 0x5643432ed362 <unknown>\n#9 0x56434330bae2 <unknown>\n#10 0x5643432ed103 <unknown>\n#11 0x5643432be1ba <unknown>\n#12 0x5643432beb8e <unknown>\n#13 0x56434355559b <unknown>\n#14 0x56434355934b <unknown>\n#15 0x564343541681 <unknown>\n#16 0x564343559eb2 <unknown>\n#17 0x5643435266af <unknown>\n#18 0x564343580428 <unknown>\n#19 0x564343580600 <unknown>\n#20 0x56434358ff84 <unknown>\n#21 0x7f507d694ac3 <unknown>",
        "time" : {
          "start" : 1714098897156,
          "stop" : 1714098897181,
          "duration" : 25
        }
      }, {
        "uid" : "c0cd7fc356196265",
        "reportUrl" : "https://Nat754.github.io/PulseWave/5//#testresult/c0cd7fc356196265",
        "status" : "passed",
        "time" : {
          "start" : 1714014736193,
          "stop" : 1714014736622,
          "duration" : 429
        }
      }, {
        "uid" : "2502ae3a96adff61",
        "reportUrl" : "https://Nat754.github.io/PulseWave/211//#testresult/2502ae3a96adff61",
        "status" : "passed",
        "time" : {
          "start" : 1713946249157,
          "stop" : 1713946249586,
          "duration" : 429
        }
      }, {
        "uid" : "9750530a50be9",
        "reportUrl" : "https://Nat754.github.io/PulseWave/4//#testresult/9750530a50be9",
        "status" : "passed",
        "time" : {
          "start" : 1713926041231,
          "stop" : 1713926041660,
          "duration" : 429
        }
      }, {
        "uid" : "f32d39f1302b1a4",
        "reportUrl" : "https://Nat754.github.io/PulseWave/211//#testresult/f32d39f1302b1a4",
        "status" : "passed",
        "time" : {
          "start" : 1713901927236,
          "stop" : 1713901927664,
          "duration" : 428
        }
      }, {
        "uid" : "cea17ceac1a5ac04",
        "reportUrl" : "https://Nat754.github.io/PulseWave/210//#testresult/cea17ceac1a5ac04",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome-headless-shell=123.0.6312.122); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x5636b38d7863 <unknown>\n#1 0x5636b35cd8c6 <unknown>\n#2 0x5636b35d2e75 <unknown>\n#3 0x5636b35d4e88 <unknown>\n#4 0x5636b3659c17 <unknown>\n#5 0x5636b363a5a2 <unknown>\n#6 0x5636b3658c19 <unknown>\n#7 0x5636b363a343 <unknown>\n#8 0x5636b360b593 <unknown>\n#9 0x5636b360bf5e <unknown>\n#10 0x5636b389b84b <unknown>\n#11 0x5636b389f7a5 <unknown>\n#12 0x5636b3889571 <unknown>\n#13 0x5636b38a0332 <unknown>\n#14 0x5636b386e87f <unknown>\n#15 0x5636b38c6728 <unknown>\n#16 0x5636b38c68fb <unknown>\n#17 0x5636b38d69b4 <unknown>\n#18 0x7f006f894ac3 <unknown>",
        "time" : {
          "start" : 1713886181819,
          "stop" : 1713886182100,
          "duration" : 281
        }
      }, {
        "uid" : "3b8070ae9cc7cec3",
        "reportUrl" : "https://Nat754.github.io/PulseWave/209//#testresult/3b8070ae9cc7cec3",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1713884065745,
          "stop" : 1713884066162,
          "duration" : 417
        }
      }, {
        "uid" : "94adff7caa95c531",
        "reportUrl" : "https://Nat754.github.io/PulseWave/209//#testresult/94adff7caa95c531",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1713882599959,
          "stop" : 1713882600382,
          "duration" : 423
        }
      }, {
        "uid" : "68670ffda34c0302",
        "reportUrl" : "https://Nat754.github.io/PulseWave/208//#testresult/68670ffda34c0302",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1713879777223,
          "stop" : 1713879777651,
          "duration" : 428
        }
      } ]
    },
    "tags" : [ "regress" ]
  },
  "source" : "1330d40f5b83a04.json",
  "parameterValues" : [ "'chrome'" ]
}