{
  "uid" : "91fd75db42b4bba6",
  "name" : "POST Создать доску",
  "fullName" : "tests.test_api.test_api.TestAPI#test_post_api_workspace_id_boards",
  "historyId" : "e0c89310e54d7f413d275ba53f8bf728",
  "time" : {
    "start" : 1714827336629,
    "stop" : 1714827340828,
    "duration" : 4199
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
  "statusTrace" : "self = <tests.test_api.test_api.TestAPI object at 0x7fc41d7a6570>\nuse_api_base = <api_testing.api_base.ApiBase object at 0x7fc41d117560>\n\n    @pytest.mark.xfail(reazon='Bug')\n    @allure.title(\"POST Создать доску\")\n    def test_post_api_workspace_id_boards(self, use_api_base):\n        jwt = use_api_base.create_jwt(email1, password0)\n        workspace_id = use_api_base.get_workspace_id()\n        url = f'{self.constant.BASE_URL}api/workspace/{workspace_id}/boards/'\n        response = requests.post(url, headers={'accept': 'application/json', 'Authorization': f\"\"\"{jwt}\"\"\"},\n                                 json=self.constant.BOARD_CREATE | {\"work_space\": f\"{workspace_id}\"})\n>       Assertions.assert_status_code(response, self.code.STATUS_201)\n\ntests/test_api/test_api.py:209: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>, expected_status_code = 201\n\n    @staticmethod\n    def assert_status_code(response: Response, expected_status_code: int):\n        actual_status_code = response.status_code\n        with allure.step(f\"Expected status {expected_status_code}\"):\n>           assert actual_status_code == expected_status_code, \\\n                f\"Unexpected status code. Expected: {expected_status_code}. Actual: {actual_status_code}\"\nE           AssertionError: Unexpected status code. Expected: 201. Actual: 500\n\napi_testing/assertions.py:11: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "use_api_base",
    "time" : {
      "start" : 1714827336629,
      "stop" : 1714827336629,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1714827258320,
      "stop" : 1714827258320,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1714827258303,
      "stop" : 1714827258320,
      "duration" : 17
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "skipped",
    "statusMessage" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
    "statusTrace" : "self = <tests.test_api.test_api.TestAPI object at 0x7fc41d7a6570>\nuse_api_base = <api_testing.api_base.ApiBase object at 0x7fc41d117560>\n\n    @pytest.mark.xfail(reazon='Bug')\n    @allure.title(\"POST Создать доску\")\n    def test_post_api_workspace_id_boards(self, use_api_base):\n        jwt = use_api_base.create_jwt(email1, password0)\n        workspace_id = use_api_base.get_workspace_id()\n        url = f'{self.constant.BASE_URL}api/workspace/{workspace_id}/boards/'\n        response = requests.post(url, headers={'accept': 'application/json', 'Authorization': f\"\"\"{jwt}\"\"\"},\n                                 json=self.constant.BOARD_CREATE | {\"work_space\": f\"{workspace_id}\"})\n>       Assertions.assert_status_code(response, self.code.STATUS_201)\n\ntests/test_api/test_api.py:209: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>, expected_status_code = 201\n\n    @staticmethod\n    def assert_status_code(response: Response, expected_status_code: int):\n        actual_status_code = response.status_code\n        with allure.step(f\"Expected status {expected_status_code}\"):\n>           assert actual_status_code == expected_status_code, \\\n                f\"Unexpected status code. Expected: {expected_status_code}. Actual: {actual_status_code}\"\nE           AssertionError: Unexpected status code. Expected: 201. Actual: 500\n\napi_testing/assertions.py:11: AssertionError",
    "steps" : [ {
      "name" : "Получить access токен пользователя на емайл",
      "time" : {
        "start" : 1714827336629,
        "stop" : 1714827337739,
        "duration" : 1110
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Получить id рабочего пространства",
      "time" : {
        "start" : 1714827337740,
        "stop" : 1714827339837,
        "duration" : 2097
      },
      "status" : "passed",
      "steps" : [ {
        "name" : "Получить access токен пользователя на емайл",
        "time" : {
          "start" : 1714827337740,
          "stop" : 1714827338891,
          "duration" : 1151
        },
        "status" : "passed",
        "steps" : [ ],
        "attachments" : [ ],
        "parameters" : [ ],
        "stepsCount" : 0,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : false,
        "hasContent" : false
      } ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 1,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "Expected status 201",
      "time" : {
        "start" : 1714827340828,
        "stop" : 1714827340828,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: Unexpected status code. Expected: 201. Actual: 500\n",
      "statusTrace" : "  File \"/home/runner/work/PulseWave/PulseWave/api_testing/assertions.py\", line 11, in assert_status_code\n    assert actual_status_code == expected_status_code, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Тестирование API"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(reazon='Bug')"
  }, {
    "name" : "parentSuite",
    "value" : "tests.test_api"
  }, {
    "name" : "suite",
    "value" : "test_api"
  }, {
    "name" : "subSuite",
    "value" : "TestAPI"
  }, {
    "name" : "host",
    "value" : "fv-az1435-516"
  }, {
    "name" : "thread",
    "value" : "2345-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_api.test_api"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 19,
        "passed" : 0,
        "unknown" : 0,
        "total" : 19
      },
      "items" : [ {
        "uid" : "ff3da079c1cbb96",
        "reportUrl" : "https://Nat754.github.io/PulseWave/14//#testresult/ff3da079c1cbb96",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 'access'",
        "time" : {
          "start" : 1714789018780,
          "stop" : 1714789020634,
          "duration" : 1854
        }
      }, {
        "uid" : "d2872ad6208502ee",
        "reportUrl" : "https://Nat754.github.io/PulseWave/13//#testresult/d2872ad6208502ee",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 'access'",
        "time" : {
          "start" : 1714702882750,
          "stop" : 1714702884469,
          "duration" : 1719
        }
      }, {
        "uid" : "94763f044990a415",
        "reportUrl" : "https://Nat754.github.io/PulseWave/12//#testresult/94763f044990a415",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 'access'",
        "time" : {
          "start" : 1714616335175,
          "stop" : 1714616336348,
          "duration" : 1173
        }
      }, {
        "uid" : "cce4850779d6e8f9",
        "reportUrl" : "https://Nat754.github.io/PulseWave/11//#testresult/cce4850779d6e8f9",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 'access'",
        "time" : {
          "start" : 1714530270978,
          "stop" : 1714530272161,
          "duration" : 1183
        }
      }, {
        "uid" : "d964c9d1affc703c",
        "reportUrl" : "https://Nat754.github.io/PulseWave/10//#testresult/d964c9d1affc703c",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host='owa.pulsewave.ru', port=443): Max retries exceeded with url: /auth/jwt/create/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17c7d8a4b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1714443495670,
          "stop" : 1714443496051,
          "duration" : 381
        }
      }, {
        "uid" : "ba47e04816aa5dd2",
        "reportUrl" : "https://Nat754.github.io/PulseWave/9//#testresult/ba47e04816aa5dd2",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host='owa.pulsewave.ru', port=443): Max retries exceeded with url: /auth/jwt/create/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7971dcce60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1714357170649,
          "stop" : 1714357171136,
          "duration" : 487
        }
      }, {
        "uid" : "2850d95049c8afaf",
        "reportUrl" : "https://Nat754.github.io/PulseWave/8//#testresult/2850d95049c8afaf",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nrequests.exceptions.SSLError: HTTPSConnectionPool(host='owa.pulsewave.ru', port=443): Max retries exceeded with url: /auth/jwt/create/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))",
        "time" : {
          "start" : 1714270956908,
          "stop" : 1714270957225,
          "duration" : 317
        }
      }, {
        "uid" : "10e1fad170d1a706",
        "reportUrl" : "https://Nat754.github.io/PulseWave/7//#testresult/10e1fad170d1a706",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1714184334488,
          "stop" : 1714184339192,
          "duration" : 4704
        }
      }, {
        "uid" : "2b61c7beec9efb35",
        "reportUrl" : "https://Nat754.github.io/PulseWave/6//#testresult/2b61c7beec9efb35",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1714147899499,
          "stop" : 1714147903623,
          "duration" : 4124
        }
      }, {
        "uid" : "eb560f32f77ab537",
        "reportUrl" : "https://Nat754.github.io/PulseWave/6//#testresult/eb560f32f77ab537",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1714097956406,
          "stop" : 1714097960247,
          "duration" : 3841
        }
      }, {
        "uid" : "27cfa17f2719eab",
        "reportUrl" : "https://Nat754.github.io/PulseWave/5//#testresult/27cfa17f2719eab",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1714013883407,
          "stop" : 1714013887423,
          "duration" : 4016
        }
      }, {
        "uid" : "cd19046ea86e17cc",
        "reportUrl" : "https://Nat754.github.io/PulseWave/211//#testresult/cd19046ea86e17cc",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1713945325173,
          "stop" : 1713945329523,
          "duration" : 4350
        }
      }, {
        "uid" : "c5fddfc7e82a0d38",
        "reportUrl" : "https://Nat754.github.io/PulseWave/4//#testresult/c5fddfc7e82a0d38",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1713925146316,
          "stop" : 1713925150003,
          "duration" : 3687
        }
      }, {
        "uid" : "56f9bbd4834746d",
        "reportUrl" : "https://Nat754.github.io/PulseWave/211//#testresult/56f9bbd4834746d",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1713900953634,
          "stop" : 1713900957845,
          "duration" : 4211
        }
      }, {
        "uid" : "3038d14c709a2199",
        "reportUrl" : "https://Nat754.github.io/PulseWave/210//#testresult/3038d14c709a2199",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1713885060746,
          "stop" : 1713885066291,
          "duration" : 5545
        }
      }, {
        "uid" : "a4c10868a0d58be3",
        "reportUrl" : "https://Nat754.github.io/PulseWave/209//#testresult/a4c10868a0d58be3",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1713882996489,
          "stop" : 1713883001077,
          "duration" : 4588
        }
      }, {
        "uid" : "5f1417894d06d2ff",
        "reportUrl" : "https://Nat754.github.io/PulseWave/209//#testresult/5f1417894d06d2ff",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1713881479583,
          "stop" : 1713881484327,
          "duration" : 4744
        }
      }, {
        "uid" : "c509c449f6194fdc",
        "reportUrl" : "https://Nat754.github.io/PulseWave/208//#testresult/c509c449f6194fdc",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nAssertionError: Unexpected status code. Expected: 201. Actual: 500",
        "time" : {
          "start" : 1713878656164,
          "stop" : 1713878660753,
          "duration" : 4589
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail(reazon='Bug')" ]
  },
  "source" : "91fd75db42b4bba6.json",
  "parameterValues" : [ ]
}